### ISSUE TITLE
Add inServer to Docker Container

### ISSUE THREAD

**Issue by tianosouza** [amaurygomes/inServer#1]
We need to add the `inServer` application to a Docker container to facilitate development and deployment. This will involve setting up a Dockerfile and a `docker-compose.yml` file to manage the necessary services.

**Tasks:**

1. **Create the Dockerfile:**
   - Base it on an appropriate Node.js image (e.g., `node:18`).
   - Install necessary dependencies (Fastify, Drizzle ORM, TypeScript, Zod, etc.).
   - Copy the application source code into the container.
   - Configure the container to run the application with TypeScript (e.g., using `ts-node`).
   - Set up environment variables and necessary configuration files.

2. **Create the docker-compose.yml file:**
   - Define the necessary services (e.g., web, database, Redis, etc.).
   - Configure volumes and environment variables.
   - Set up networks if needed.

3. **Update `.dockerignore`:**
   - Add files and directories that should not be copied into the container (e.g., `node_modules`, `dist`, etc.).

4. **Test the container:**
   - Build and run the container.
   - Verify that the application is functioning correctly within the container environment.
   - Perform integration tests to ensure that all services work well together.

**Notes:**
- Ensure that the Dockerfile and docker-compose.yml are well-documented for future updates and maintenance.
- Verify that all necessary environment variables are correctly configured, especially for database configuration and other dependencies.

**References:**
- [Docker Documentation](https://docs.docker.com/)
- [Docker Compose Documentation](https://docs.docker.com/compose/)
- [Fastify Documentation](https://www.fastify.io/docs/latest/)
- [Drizzle ORM Documentation](https://drizzle.team/docs/)
- [TypeScript Documentation](https://www.typescriptlang.org/docs/)
- [Zod Documentation](https://zod.dev/)

**Comment by amaurygomes** [comment]
I will implement the solution to containerize the inServer application using Docker to facilitate development and deployment.

Observations:

I will ensure that the Dockerfile and docker-compose.yml are well-documented for future updates and maintenance.

I will verify that all necessary environment variables are correctly configured, especially for the database and other dependencies. 

Thank you!
